name: "create release"

on:
  workflow_run:
    workflows: ["godot-ci export"]
    types:
      - completed

permissions:
  contents: write
  actions: read

jobs:
  create:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Compute next version
        run: |
          git fetch --tags

          LATEST=$(git tag --list "0.0.*" --sort=-v:refname | head -n 1)

          if [ -z "$LATEST" ]; then
            PATCH=1
          else
            PATCH=$(echo "$LATEST" | awk -F. '{print $3+1}')
          fi

          echo "TAG=0.0.$PATCH" >> $GITHUB_ENV

      - name: Download godot-ci artifacts
        uses: actions/download-artifact@v8
        with:
          run-id: ${{ github.event.workflow_run.id }}
          path: artifacts

      - name: Create prerelease with assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          prerelease: true
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
